# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sproutee < Formula
  desc "A powerful CLI tool for efficient Git worktree management with automated file copying and multi-editor integration"
  homepage "https://github.com/daisuke310vvv/sproutee"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/daisuke310vvv/sproutee/releases/download/v0.2.0/sproutee_Darwin_x86_64.tar.gz"
      sha256 "ef86d9f7021f9b4ca89e40325caac6792bbc0050e73654aeefe7650c27ae6a90"

      def install
        bin.install "sproutee"
      end
    end
    on_arm do
      url "https://github.com/daisuke310vvv/sproutee/releases/download/v0.2.0/sproutee_Darwin_arm64.tar.gz"
      sha256 "f4d3e28fba1ebefe1874b1ae1e6ffce7f55f45e290cf87d32b7da864cc47f77f"

      def install
        bin.install "sproutee"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/daisuke310vvv/sproutee/releases/download/v0.2.0/sproutee_Linux_x86_64.tar.gz"
        sha256 "fc4e7338858714a9e51bd64caddc5042a1746e769386ecf5bb791df97382d103"

        def install
          bin.install "sproutee"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/daisuke310vvv/sproutee/releases/download/v0.2.0/sproutee_Linux_armv6.tar.gz"
        sha256 "5b44d23a2e5787911a6fc2d94d4de28b5e09680596c33641a3ba7e0cae465cf5"

        def install
          bin.install "sproutee"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/daisuke310vvv/sproutee/releases/download/v0.2.0/sproutee_Linux_arm64.tar.gz"
        sha256 "5ac9000fee5d6432799c83dfedbf3c9733ce87b20805c117f5e2c74e19c57fdf"

        def install
          bin.install "sproutee"
        end
      end
    end
  end

  test do
    system "#{bin}/sproutee", "--help"
  end
end
