# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sproutee < Formula
  desc "A powerful CLI tool for efficient Git worktree management with automated file copying and multi-editor integration"
  homepage "https://github.com/daisuke310vvv/sproutee"
  version "0.3.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/daisuke310vvv/sproutee/releases/download/v0.3.1/sproutee_Darwin_x86_64.tar.gz"
      sha256 "96d02af5e4a136030b3cddefafc55d659388977959c01e12d5eb35346197ca8f"

      def install
        bin.install "sproutee"
      end
    end
    on_arm do
      url "https://github.com/daisuke310vvv/sproutee/releases/download/v0.3.1/sproutee_Darwin_arm64.tar.gz"
      sha256 "45950661a812a24a7519ca4baccd75ea032baa23984dcd3d13a7503bedf28b20"

      def install
        bin.install "sproutee"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/daisuke310vvv/sproutee/releases/download/v0.3.1/sproutee_Linux_x86_64.tar.gz"
        sha256 "07125db3d288e209c7c386ec23486374aa7e1774ea472d2fdf023e37e30615fa"

        def install
          bin.install "sproutee"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/daisuke310vvv/sproutee/releases/download/v0.3.1/sproutee_Linux_armv6.tar.gz"
        sha256 "2b48c53b40617dc6817d3460982bae7b9edf415d5a48099d88b15c45c272cdf6"

        def install
          bin.install "sproutee"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/daisuke310vvv/sproutee/releases/download/v0.3.1/sproutee_Linux_arm64.tar.gz"
        sha256 "da09e94c68a2ea00ff23270886391d2c6b8ce2b78edcb111d8176d14c20764fb"

        def install
          bin.install "sproutee"
        end
      end
    end
  end

  test do
    system "#{bin}/sproutee", "--help"
  end
end
